#! /usr/bin/python
"""
	This index page includes 2 kinds of searches: gene names (IDs and symbols) search and gene functions. 
	Each directs to genesearch.py and gosearch.py, respectively.
"""
import cgi

if __name__=='__main__':
	print 'Content-type: text/html'
	print
	print '<html><head><title>'
	print 'Arabdopsis Athaliana Microarray Data Browser'
	print '</title></head>'
	print '<body>'
	print '<div id="topbanner">'
	print '<h1>Welcome to Arabidopsis Athaliana Microarray Database!</h1>'
	print '<p></p>'
	print '<p>Gene search is the only one you can enter multiple entries separated by comma " , ".</p>'
	print '</div>'
	print '<div id="mainbody">'
	print '<table cellpadding=5 style="border-color:black;border-style:solid;border-width:thin" width="1000" align="center">'
	print '<tbody>'
	print '<form action="genesearch.py">'
	print '<tr><td>'
	print '<p><b>Search by gene name</b></p></td></tr>'
	print '<tr><td>'
	print '<input type=radio name=genename value="1" checked>Probe ID</td>'
	print '<td>'
	print '<input type=radio name=genename value="2">Gene Symbol</td>'
	print '<td>'
	print '<input type=radio name=genename value="3">Gene ID</td>'
	print '<td>'
	print '<input type=text name=gnsearch value=""></td>'
	print '</tr>'
	print '<tr>'
	print '<td>'
	print '<p><b>'
	print 'Search by experiment features'
	print '</b></p>'
	print '</td>'
	print '</tr>'
	print '<tr><td>'
	print '</td><td><select size="1" name="exp1"><option value="1">----</option><option value="2">Genetic Background</option><option value="3">Tissue</option><option value="4">Treatment</option></select></td><td>'
	print 'contains'
	print '</td><td><input type=text name="expsearch1" value=""></td></tr>'
	print '<tr><td>'
	print 'AND'
	print '</td><td><select size="1" name="exp2"><option value="1">----</option><option value="2">Genetic Background</option><option value="3">Tissue</option><option value="4">Treatment</option></select></td><td>'
	print 'contains'
	print '</td><td><input type=text name="expsearch2" value=""></td></tr>'
	print '<tr><td>'
	print 'AND'
	print '</td><td><select size="1" name="exp3"><option value="1">----</option><option value="2">Genetic Background</option><option value="3">Tissue</option><option value="4">Treatment</option></select></td><td>'
	print 'contains'
	print '</td><td><input type=text name="expsearch3" value=""></td></tr>'
	print '<tr><td>'
	print '<input type=submit></td></tr>'
	print '</form>'
	print '</tbody>'
	print '</table>'
	print '<table cellpadding=5 style="border-color:black;border-style:solid;border-width:thin" width="1000" align="center">'
	print '<tbody>'
	print '<form action="gosearch.py">'
	print '<tr>'
	print '<td>'
	print '<p><b>'
	print 'Search by GO terms'
	print '</b></p>'
	print '</td>'
	print '</tr>'
	print '<tr><td>'
	print '</td><td><select size="1" name="genefunction1"><option value="1">----</option><option value="2">GO Biological Process</option><option value="3">GO Cellular Component</option><option value="4">GO Molecular Function</option></select></td><td>'
	print 'contains'
	print '</td><td><input type=text name="gfsearch1" value=""></td></tr>'
	print '<tr><td>'
	print 'AND'
	print '</td><td><select size="1" name="genefunction2"><option value="1">----</option><option value="2">GO Biological Process</option><option value="3">GO Cellular Component</option><option value="4">GO Molecular Function</option></select></td><td>'
	print 'contains'
	print '</td><td><input type=text name="gfsearch2" value=""></td></tr>'
	print '<tr><td>'
	print 'AND'
	print '</td><td><select size="1" name="genefunction3"><option value="1">----</option><option value="2">GO Biological Process</option><option value="3">GO Cellular Component</option><option value="4">GO Molecular Function</option></select></td><td>'
	print 'contains'
	print '</td><td><input type=text name="gfsearch3" value=""></td></tr>'
	print '<tr>'
	print '<td>'
	print '<p><b>'
	print 'Search by experiment features'
	print '</b></p>'
	print '</td>'
	print '</tr>'
	print '<tr><td>'
	print '</td><td><select size="1" name="exp1"><option value="1">----</option><option value="2">Genetic Background</option><option value="3">Tissue</option><option value="4">Treatment</option></select></td><td>'
	print 'contains'
	print '</td><td><input type=text name="expsearch1" value=""></td></tr>'
	print '<tr><td>'
	print 'AND'
	print '</td><td><select size="1" name="exp2"><option value="1">----</option><option value="2">Genetic Background</option><option value="3">Tissue</option><option value="4">Treatment</option></select></td><td>'
	print 'contains'
	print '</td><td><input type=text name="expsearch2" value=""></td></tr>'
	print '<tr><td>'
	print 'AND'
	print '</td><td><select size="1" name="exp3"><option value="1">----</option><option value="2">Genetic Background</option><option value="3">Tissue</option><option value="4">Treatment</option></select></td><td>'
	print 'contains'
	print '</td><td><input type=text name="expsearch3" value=""></td></tr>'
	print '<tr><td colspan="4"><input type=submit></td></tr>'
	print '</form>'
	print '</tbody>'
	print '</table>'
	print '</div>'
	print '</form>'
	print '</body>'
	print '</html>'
